---
changelog:
  - changes:
      - text: 'Support Signals'
        type: improvement
    date: 2020-03-19
    version: v0.0.8-beta
  - changes:
      - text: 'Fix support for membership'
        type: improvement
    date: 2020-02-12
    version: v0.0.5-beta
  - changes:
      - text: 'travis setup'
        type: feature
    date: 2019-08-22
    version: v0.0.4-beta
  - changes:
      - text: 'first public version'
        type: feature
    date: 2019-08-14
    version: v0.0.2-beta
files:
  - dist/index.js
name: pubnub-redux
schema: 1
scm: github.com/pubnub/redux
version: '0.0.6'
